server:
  port: 9000
  servlet:
    session:
      cookie:
        name: auth-server

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_authorization?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ${JDBC_PASS:123456}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
